Repository hove-io/navitia, pull requests merged in 2018-03, with the labels that each got.

#2364 fix failing ridesharing test with protobuf 2.6
  source/jormungandr/tests/instant_system_new_default_routing_tests.py
Labels: not_in_changelog

#2357 Tyr : Task to delete old jobs in db
  source/navitiacommon/navitiacommon/models.py
  source/tyr/tests/conftest.py
  source/tyr/tests/integration/autocomplete_test.py
  source/tyr/tests/integration/conftest.py
  source/tyr/tests/integration/datapost_test.py
  source/tyr/tests/integration/instance_test.py
  source/tyr/tests/integration/migrate_poi_to_osm_test.py
  source/tyr/tests/integration/poi_type_json_test.py
  source/tyr/tests/integration/purge_test.py
  source/tyr/tests/integration/users_test.py
  source/tyr/tyr/__init__.py
  source/tyr/tyr/command/purge.py
  source/tyr/tyr/default_settings.py
  source/tyr/tyr/helper.py
  source/tyr/tyr/tasks.py
Labels: do_not_merge

#2370 kraken: handle route_schedule with a 2 stop_areas filter
  source/jormungandr/tests/departure_board_tests.py
  source/time_tables/departure_boards.cpp
  source/time_tables/passages.cpp
  source/time_tables/request_handle.cpp
  source/time_tables/request_handle.h
  source/time_tables/route_schedules.cpp
Labels: hotfix

#2371 ptref: add a link between PhysicalMode and JourneyPattern in the graph
  source/ptreferential/ptref_graph.cpp
  source/type/data.cpp
Labels: hotfix

#2369 Doc: fix print function
  script_release.py
Labels: not_in_changelog
