Repository hove-io/navitia, pull requests merged in 2019-06, with the labels that each got.

#2821 kraken: fix autocomplete scores after rt update
  source/jormungandr/tests/kirin_realtime_tests.py
  source/kraken/maintenance_worker.cpp
Labels: hotfix

#2819 Doc: Update readme.rst
  readme.rst
Labels: not_in_changelog

#2820 Doc: Update explore.md
  documentation/slate/source/includes/explore.md
Labels: not_in_changelog

#2828 Doc: cost type modified to string
  documentation/slate/source/includes/apis.md
Labels: not_in_changelog

#2835 Jormun: mypy doesn't like protobuf types
  source/jormungandr/jormungandr/schedule.py
Labels: ok_to_merge

#2808 [Jormun] Integration test for ticket in journeys response
  source/jormungandr/jormungandr/interfaces/v1/serializer/journey.py
  source/jormungandr/tests/journey_common_tests.py
  source/jormungandr/tests/tests_mechanism.py
  source/routing/tests/routing_api_test_data.h
Labels: ok_to_merge

#2812 Jormungandr: equipment_reports api with uri filter
  source/jormungandr/jormungandr/interfaces/common.py
  source/jormungandr/jormungandr/interfaces/v1/Calendars.py
  source/jormungandr/jormungandr/interfaces/v1/Disruptions.py
  source/jormungandr/jormungandr/interfaces/v1/EquipmentReports.py
  source/jormungandr/jormungandr/interfaces/v1/LineReports.py
  source/jormungandr/jormungandr/interfaces/v1/Schedules.py
  source/jormungandr/jormungandr/interfaces/v1/Uri.py
  source/jormungandr/tests/equipment_tests.py
Labels: ok_to_merge

#2814 jormungandr: equipment_reports abort is tested
  source/jormungandr/tests/equipment_tests.py
Labels: ok_to_merge

#2811 [Doc] Realtime integration in Navitia
  documentation/slate/source/images/delay.png
  documentation/slate/source/images/modified_service.png
  documentation/slate/source/images/reduced_service.png
  documentation/slate/source/includes/apis.md
  documentation/slate/source/includes/departures.md
  documentation/slate/source/includes/objects.md
  documentation/slate/source/includes/realtime.md
  documentation/slate/source/index.md
Labels: ok_to_merge

#2815 Jormungandr: add a test to ensure that jormungandr does not read bragi's id
  source/jormungandr/tests/bragi_autocomplete_tests.py
Labels: ok_to_merge

#2816 Kraken: Add ability to configure max core dump file size
  source/kraken/configuration.cpp
  source/kraken/configuration.h
  source/kraken/kraken_zmq.cpp
Labels: ok_to_merge

#2826 [Tyr] Return error when provider not found + test
  source/tyr/tests/integration/instance_test.py
  source/tyr/tyr/resources.py
Labels: ok_to_merge

#2829 Kraken: Fix the way best journey is picked (filter)
  source/ed/osm2ed.cpp
  source/ed/osm2ed.h
  source/routing/journey.h
  source/routing/raptor_api.cpp
  source/routing/tests/journey_test.cpp
  source/routing/tests/routing_api_test.cpp
Labels: ok_to_merge
