Repository hove-io/navitia, pull requests merged in 2019-03, with the labels that each got.

#2692 kraken: delete a queue after a timeout for a reload from kirin
  source/kraken/maintenance_worker.cpp
Labels: ok_to review

#2697 Doc: correction on stop_points' order in `/routes?depth=3`
  documentation/slate/source/includes/interface.md
Labels: not_in_changelog

#2705 Doc: small detail on fare_extention
  documentation/ntfs/ntfs_fare_extension_fr.md
Labels: not_in_changelog

#2724 Kraken: Add RT route dynamically
  source/jormungandr/tests/kirin_realtime_tests.py
  source/kraken/apply_disruption.cpp
  source/kraken/apply_disruption.h
  source/kraken/data_manager.h
  source/kraken/maintenance_worker.cpp
  source/kraken/realtime.h
  source/kraken/tests/data_manager_test.cpp
  source/kraken/tests/realtime_test.cpp
  source/type/pt_data.cpp
  source/type/pt_data.h
Labels: merge_after_release
