Repository hove-io/navitia, pull requests merged in 2019-10, with the labels that each got.

#2970 Enable mergify
  .mergify.yml
Labels: not_in_changelog

#2977 [Jormungandr] use best PT journey for too_many_connections_filter
  source/jormungandr/jormungandr/scenarios/journey_filter.py
  source/jormungandr/jormungandr/scenarios/new_default.py
  source/jormungandr/jormungandr/scenarios/qualifier.py
  source/jormungandr/jormungandr/scenarios/tests/new_default_tests.py
  source/jormungandr/tests/stif_tests.py
Labels: do_not_merge

#2972 Doc: IRC to riot migration (first step)
  readme.rst
Labels: not_in_changelog

#2995 Treat 'blue_anime' Jenkins' job as OK
  source/scripts/checkJenkinsJob.sh
Labels: not_in_changelog

#2994 ed: use fare_zone_id instead of zone_id in fusio_parser
  fixtures/ed/ntfs/stops.txt
  fixtures/ed/ntfs_v5/stops.txt
  source/ed/connectors/fusio_parser.cpp
  source/ed/tests/fusioparser_test.cpp
Labels: do_not_merge

#2975 jormun: use serpy fork from pypi
  source/jormungandr/requirements.txt
Labels: not_in_changelog

#2996 Mergify smart rebase
  .mergify.yml
  .pre-commit-config.yaml
Labels: not_in_changelog

#2973 jormun: use flask_restful from upstream
  source/jormungandr/requirements.txt
  source/tyr/requirements.txt
Labels: merge_after_release, not_in_changelog

#3005 add crow_fly
  documentation/slate/source/includes/apis.md
Labels: documentation, not_in_changelog

#3006 jormun: external_code finally works with coverage on every Uri API
  source/jormungandr/jormungandr/interfaces/v1/Uri.py
  source/jormungandr/tests/ptref_tests.py
  source/tests/mock-kraken/main_ptref_test.cpp
Labels: merge_after_release

#3010 Doc: Update to explain more data_freshness impact on collection filters
  documentation/slate/source/includes/apis.md
  documentation/slate/source/includes/realtime.md
  source/jormungandr/jormungandr/interfaces/v1/journey_common.py
Labels: documentation
