Repository hove-io/navitia, pull requests merged in 2019-07, with the labels that each got.

#2838 Use mypy for every projects
  .pre-commit-config.yaml
  source/eitri/ed_handler.py
  source/tyr/migrations/env.py
  source/tyr/tests/conftest.py
  source/tyr/tests/integration/purge_test.py
Labels: ok_to review

#2834 [Tyr] API v1
  source/navitiacommon/navitiacommon/models/equipments_providers.py
  source/tyr/tests/integration/equipment_providers_test.py
  source/tyr/tests/integration/v1_test.py
  source/tyr/tyr/api.py
  source/tyr/tyr/default_settings.py
  source/tyr/tyr/formats.py
  source/tyr/tyr/resources.py
Labels: merge_after_release

#2827 Kraken: Visibility of an address in autocomplete fixed
  source/georef/georef.h
  source/jormungandr/tests/kirin_realtime_tests.py
  source/routing/tests/routing_api_test_data.h
  source/type/data.cpp
Labels: ++data_version, merge_after_release

#2839 [Jormun] Adding street_network_configuraton in db
  source/navitiacommon/navitiacommon/default_values.py
  source/navitiacommon/navitiacommon/models/__init__.py
  source/navitiacommon/navitiacommon/models/streetnetwork_backend.py
  source/tyr/migrations/versions/57f52a929056_street_network_configuration_db.py
Labels: modify_db

#2786 script : Install dev env + run Navitia demo
  CONTRIBUTING.md
  scripts/README.md
  scripts/build_navitia.sh
  scripts/build_setup_and_run_navitia_demo.sh
  scripts/ubuntu_bionic_disco_dev_env_install.sh
  source/cmake_modules/ThirdParty.cmake
Labels: ok_to_merge
