Repository hove-io/navitia, pull requests merged in 2019-04, with the labels that each got.

#2734 jormungandr: Test on departures and stop_schedules added
  source/jormungandr/tests/kirin_realtime_tests.py
Labels: not_in_changelog

#2746 [Kraken] Replace Clang-format hooks with navitia-pre-commit's one
  .pre-commit-config.yaml
  .travis.yml
Labels: not_in_changelog

#2745 Doc: precision on calendar's period
  documentation/ntfs/ntfs_fr.md
Labels: not_in_changelog

#2747 [Doc] Documentation around clang-format
  CONTRIBUTING.md
  build_navitia.sh
Labels: documentation, not_in_changelog

#2760 Doc: update hotfix doc
  readme_release.md
  script_release.py
Labels: not_in_changelog

#2761 Python: update SQLAlchemy requirements
  source/cities/requirements.txt
  source/eitri/requirements.txt
  source/jormungandr/requirements.txt
  source/navitiacommon/navitiacommon/models/equipments_providers.py
  source/sql/requirements.txt
  source/tyr/migrations/versions/2e0ac7e0a7a7_add_traveler_profile_table.py
  source/tyr/migrations/versions/3e56c7e0a4a4_create_billing_plan_table.py
  source/tyr/requirements.txt
Labels: merge_after_release

#2756 Osm2ed improve association of Way to Admin
  source/ed/osm2ed.cpp
Labels: merge_after_release
