Repository hove-io/navitia, pull requests merged in 2019-08, with the labels that each got.

#2907 add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: not_in_changelog

#2903 kraken: Avoid duplicate fields into last street network section
  source/routing/raptor_api.cpp
  source/routing/tests/routing_api_test.cpp
Labels: merge_after_release

#2894 Support private poi in tyr and jormungandr
  source/jormungandr/jormungandr/autocomplete/geocodejson.py
  source/jormungandr/jormungandr/instance.py
  source/jormungandr/jormungandr/interfaces/v1/test/elastic_search_tests.py
  source/jormungandr/tests/bragi_autocomplete_tests.py
  source/jormungandr/tests/tests_mechanism.py
  source/navitiacommon/navitiacommon/models/__init__.py
  source/tyr/migrations/versions/214932354af8_private_poi_dataset.py
  source/tyr/migrations/versions/858b24967ff2_metric_type_to_text.py
  source/tyr/tests/integration/mimir_test.py
  source/tyr/tyr/binarisation.py
  source/tyr/tyr/command/import_last_autocomplete_dataset.py
  source/tyr/tyr/tasks.py
Labels: merge_after_release

#2920 Fix travis ignoring error on tyr tests
  .travis.yml
  source/navitiacommon/testscommon/docker_wrapper.py
  source/tyr/tests/integration/mimir_test.py
Labels: not_in_changelog

#2911 fusio2ed: line_id is supported into grid_rel_calendar_line.txt
  fixtures/ed/ntfs_dst/grid_rel_calendar_line.txt
  fixtures/ed/ntfs_dst/lines.txt
  fixtures/ed/ntfs_dst/object_codes.txt
  source/ed/connectors/fusio_parser.cpp
  source/ed/connectors/fusio_parser.h
  source/ed/docker_tests/ed_integration_tests.cpp
  source/ed/tests/fusioparser_test.cpp
Labels: merge_after_release

#2916 Doc: Update for equipment_reports
  documentation/slate/source/includes/apis.md
  documentation/slate/source/includes/objects.md
Labels: not_in_changelog

#2927 [kraken]: remove inversed variable
  source/georef/georef.cpp
  source/georef/georef.h
Labels: hotfix

#2902 jormun: restrict bragi autocompletion to the coverage
  source/jormungandr/jormungandr/autocomplete/geocodejson.py
  source/jormungandr/jormungandr/instance.py
  source/jormungandr/jormungandr/interfaces/v1/Places.py
  source/jormungandr/jormungandr/tests/instance_tests.py
  source/jormungandr/tests/authentication_tests.py
  source/jormungandr/tests/bragi_autocomplete_tests.py
Labels: merge_after_release
