Repository hove-io/navitia, pull requests merged in 2019-05, with the labels that each got.

#2793 Kraken: handle A* clang warning
  source/georef/astar_path_finder.cpp
  source/georef/astar_path_finder.h
  source/georef/dijkstra_path_finder.cpp
  source/georef/dijkstra_path_finder.h
  source/georef/path_finder.cpp
  source/georef/path_finder.h
Labels: not_in_changelog

#2798 Doc: update release doc
  readme_release.md
  release/script_release.py
Labels: not_in_changelog

#2795 Doc: Equipment reports
  documentation/slate/CONTRIBUTING.md
  documentation/slate/source/includes/apis.md
  documentation/slate/source/includes/objects.md
Labels: not_in_changelog

#2801 Build: add pre-commit for flake8
  .flake8
  .pre-commit-config.yaml
  .travis.yml
  source/jormungandr/jormungandr/interfaces/v1/serializer/time.py
  source/jormungandr/jormungandr/resources_utils.py
  source/jormungandr/requirements_dev.txt
  source/navitiacommon/navitiacommon/utils.py
  source/sql/alembic/versions/1651f9b235f5_journey_pattern_suppression.py
Labels: waiting

#2802 Jormun : Adding min_taxi
  source/jormungandr/jormungandr/instance.py
  source/jormungandr/jormungandr/interfaces/v1/Journeys.py
  source/jormungandr/jormungandr/interfaces/v1/serializer/status.py
  source/jormungandr/jormungandr/scenarios/journey_filter.py
  source/jormungandr/jormungandr/scenarios/tests/journey_compare_tests.py
  source/jormungandr/jormungandr/scenarios/utils.py
  source/jormungandr/tests/routing_tests_experimental.py
  source/navitiacommon/navitiacommon/default_values.py
  source/navitiacommon/navitiacommon/models/__init__.py
  source/tyr/migrations/versions/5a941f98789c_add_min_taxi.py
  source/tyr/tests/integration/instance_test.py
  source/tyr/tyr/fields.py
  source/tyr/tyr/resources.py
Labels: ok_to review

#2792 Kraken : Optimisation for dijkstra
  source/georef/astar_path_finder.cpp
  source/georef/astar_path_finder.h
  source/georef/dijkstra_path_finder.cpp
  source/georef/dijkstra_path_finder.h
  source/georef/dijkstra_shortest_paths_with_heap.h
  source/georef/tests/CMakeLists.txt
  source/georef/tests/path_finder_test.cpp
  source/georef/visitor.h
Labels: ok_to review

#2804 Kraken : Using projected coord instead of real coord for astar
  source/georef/astar_path_finder.cpp
  source/georef/astar_path_finder.h
  source/georef/street_network.cpp
  source/georef/tests/georef_test.cpp
  source/georef/tests/street_network_test.cpp
Labels: ok_to review

#2810 doc: add depth param into concerned APIs doc part
  documentation/slate/source/includes/apis.md
Labels: not_in_changelog
