Repository hove-io/navitia, pull requests merged in 2020-10, with the labels that each got.

#3303 [raptor] count stay_in as a transfer in the pareto front
  source/routing/journey.cpp
Labels: ok_to_merge

#3304 [ed] Fix pickup and drop-off integrity for stay-in
  fixtures/ed/ntfs_hlp/calendar_dates.txt
  fixtures/ed/ntfs_hlp/commercial_modes.txt
  fixtures/ed/ntfs_hlp/companies.txt
  fixtures/ed/ntfs_hlp/contributors.txt
  fixtures/ed/ntfs_hlp/feed_infos.txt
  fixtures/ed/ntfs_hlp/lines.txt
  fixtures/ed/ntfs_hlp/networks.txt
  fixtures/ed/ntfs_hlp/physical_modes.txt
  fixtures/ed/ntfs_hlp/routes.txt
  fixtures/ed/ntfs_hlp/stop_times.txt
  fixtures/ed/ntfs_hlp/stops.txt
  fixtures/ed/ntfs_hlp/trip_properties.txt
  fixtures/ed/ntfs_hlp/trips.txt
  source/ed/data.cpp
  source/ed/tests/CMakeLists.txt
  source/ed/tests/fusioparser_test.cpp
  source/ed/tests/types_test.cpp
  source/ed/types.cpp
  source/ed/types.h
Labels: bina_required, ok_to review

#3310 [Github Actions] remove setenv in github actions
  .github/workflows/build_navitia_packages_for_dev.yml
  .github/workflows/build_navitia_packages_for_release.yml
Labels: not_in_changelog
