Repository hove-io/navitia, pull requests merged in 2021-11, with the labels that each got.

#3603 [CI] Run Artemis on labeled PR
  .github/workflows/build_navitia_packages_for_dev_multi_distribution.yml
Labels: run_artemis

#3605 [Jormun] Fix for direct_path walking/bss
  source/jormungandr/jormungandr/scenarios/new_default.py
  source/jormungandr/tests/routing_tests_experimental.py
Labels: run_artemis

#3606 [Jormun] Filter duplicate journey
  source/jormungandr/jormungandr/scenarios/journey_filter.py
  source/jormungandr/jormungandr/scenarios/new_default.py
Labels: run_artemis

#3604 [Jormun] Add filter for similar crow_fly
  source/jormungandr/jormungandr/scenarios/journey_filter.py
  source/jormungandr/tests/routing_tests_experimental.py
Labels: run_artemis

#3607 Diagram for ptref_grammar updated
  documentation/diagrams/pt_graph.png
  documentation/rfc/ptref_grammar.md
Labels: do_not_merge, ok_to review

#3527 Revert : Revert : [Jormun/Tyr] Add instructions language
  source/jormungandr/jormungandr/instance.py
  source/jormungandr/jormungandr/interfaces/v1/Journeys.py
  source/jormungandr/jormungandr/street_network/asgard.py
  source/jormungandr/jormungandr/street_network/kraken.py
  source/jormungandr/jormungandr/street_network/tests/asgard_test.py
  source/navitiacommon/navitiacommon/default_values.py
  source/navitiacommon/navitiacommon/models/__init__.py
  source/tyr/migrations/versions/7a77ccf8f94e_add_asgard_language.py
  source/tyr/tyr/fields.py
  source/tyr/tyr/resources.py
Labels: do_not_merge, ok_to review

#3600 Import data: Elasticsearch2 en Elasticsearch7
  source/tyr/tests/integration/conftest.py
  source/tyr/tests/integration/datapost_test.py
  source/tyr/tests/integration/helper_test.py
  source/tyr/tests/integration/mimir_test.py
  source/tyr/tyr/binarisation.py
  source/tyr/tyr/default_settings.py
  source/tyr/tyr/helper.py
  source/tyr/tyr/resources.py
  source/tyr/tyr/tasks.py
Labels: do_not_merge, ok_to review

#3614 ed: add inputs outputs and pathways inside ed db
  fixtures/ed/ntfs/stops.txt
  fixtures/ed/ntfs_v5/pathways.txt
  fixtures/ed/ntfs_v5/stops.txt
  source/ed/connectors/fusio_parser.cpp
  source/ed/connectors/fusio_parser.h
  source/ed/connectors/gtfs_parser.cpp
  source/ed/connectors/gtfs_parser.h
  source/ed/data.h
  source/ed/ed_persistor.cpp
  source/ed/ed_persistor.h
  source/ed/tests/fusioparser_test.cpp
  source/ed/types.h
  source/sql/alembic/versions/b94662e3f67e_add_input_output_and_pathway_table.py
  source/type/CMakeLists.txt
  source/type/access_point.cpp
  source/type/access_point.h
  source/type/fwd_type.h
  source/type/type_interfaces.h
Labels: ok_to review
