Repository hove-io/navitia, pull requests merged in 2021-07, with the labels that each got.

#3487 Walking transfer path
  source/jormungandr/jormungandr/interfaces/v1/Journeys.py
  source/jormungandr/jormungandr/interfaces/v1/serializer/fields.py
  source/jormungandr/jormungandr/scenarios/helper_classes/complete_pt_journey.py
  source/jormungandr/jormungandr/scenarios/helper_classes/helper_utils.py
  source/jormungandr/jormungandr/scenarios/helper_classes/streetnetwork_path.py
  source/jormungandr/tests/routing_tests_experimental.py
  source/routing/tests/routing_api_with_transfer_test_data.h
  source/tests/mock-kraken/CMakeLists.txt
  source/tests/mock-kraken/routing_with_transfer_test.cpp
Labels: ok_to review

#3503 set rabbitmq image to 3.8 in CI
  .github/workflows/workflow.yml
Labels: not_in_changelog

#3502 Revert "[Jormun/Tyr] Add instructions language"
  source/jormungandr/jormungandr/instance.py
  source/jormungandr/jormungandr/interfaces/v1/Journeys.py
  source/jormungandr/jormungandr/street_network/asgard.py
  source/jormungandr/jormungandr/street_network/kraken.py
  source/jormungandr/jormungandr/street_network/tests/asgard_test.py
  source/navitiacommon/navitiacommon/default_values.py
  source/navitiacommon/navitiacommon/models/__init__.py
  source/tyr/migrations/versions/8ede48ca4e23_add_asgard_language.py
  source/tyr/tyr/fields.py
  source/tyr/tyr/resources.py
Labels: not_in_changelog

#3510 [Ed] Do not generate connections when transfer.txt is not empty
  source/ed/data.cpp
Labels: do_not_merge
