Repository hove-io/navitia, pull requests merged in 2022-03, with the labels that each got.

#3691 Revert "access point: conceal length and traversal time"
  source/jormungandr/jormungandr/interfaces/v1/serializer/pt.py
  source/jormungandr/tests/access_points_tests.py
  source/jormungandr/tests/routing_tests_experimental.py
Labels: not_in_changelog

#3695 Modify params for indexing data in elastic search
  source/tyr/tyr/binarisation.py
  source/tyr/tyr/default_settings.py
Labels: do_not_merge

#3697 [Jormungandr] fix access point in journey
  source/jormungandr/jormungandr/interfaces/v1/serializer/journey.py
  source/jormungandr/jormungandr/interfaces/v1/serializer/pt.py
  source/jormungandr/tests/access_points_tests.py
  source/jormungandr/tests/routing_tests_experimental.py
Labels: hotfix
